image: node:12-alpine

variables:
  CI_SERVERLESS_PROFILE: default

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/

stages:
  - deploy-dev
  - deploy

before_script:
  - npm install -g serverless@1.61.0 --no-progress
  - npm install --no-progress

.deploy:
  script:
    - serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
    - echo "$STAGE"
    - serverless deploy --stage=$STAGE --verbose

test:
  stage: test
  script:
    - npm run test
  artifacts:
    reports:
      junit: junit.xml
  only:
    - merge_requests
    - master

deploy_sandbox:
  stage: deploy-dev
  extends:
    - .deploy
  only:
    - master
    - merge_requests
  environment:
    name: sandbox

deploy_production:
  stage: deploy
  extends:
    - .deploy
  only:
    - master
  when: manual
  environment:
    name: production
