image: node:current-buster-slim

variables:
  CI_SERVERLESS_PROFILE: ""

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/

stages:
  - deploy-dev
  - deploy

.deploy:
  extends:
    - .setup-aws-credentials
  before_script:
    - npm install -g serverless@1.61.0 --no-progress
    - npm install --no-progress
  script:
    - serverless deploy --verbose

deploy_sandbox:
  stage: deploy-dev
  extends:
    - .deploy
  only:
    - merge_requests
    - master
  environment:
    name: sandbox
    NODE_ENV: development

deploy_production:
  stage: deploy
  extends:
    - .deploy
  only:
    - master
  when: manual
  environment:
    name: production
    NODE_ENV: production
# include:
#   - project: 'vistaprint-org/product-catalog/pipeline-templates'
#     ref: 'master'
#     file: 'setup-aws-credentials.yaml'
