service: auth0-custom-authorizer

useDotenv: true
variablesResolutionMode: 20210326

package:
  individually: true

plugins:
  - serverless-plugin-typescript
  # - serverless-plugin-thundra
  - serverless-localstack

custom:
  endpointType: regional
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, env:NODE_ENV, 'development'}
  localstack:
    edgePort: 4566
    host: ${env:LOCALSTACK_HOSTNAME, 'https://localhost'}
    stages:
      - development
  logRetentionInDays:
    development: 7
    production: 30
  memorySize:
    development: 128
    production: 128
  provisionedConcurrency:
    development: 1
    production: 
  timeout:
    development: 900
    production: 6

provider:
  name: aws
  endpointType: ${self:custom.endpointType}
  lambdaHashingVersion: 20201221
  logRetentionInDays: ${self:custom.logRetentionInDays.${self:custom.stage}}
  memorySize: ${self:custom.memorySize.${self:custom.stage}}
  profile: 'souschef'
  region: ${self:custom.region}
  runtime: nodejs14.x
  stage: ${self:custom.stage}
  timeout: ${self:custom.timeout.${self:custom.stage}}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    thundra_agent_lambda_debugger_enable: true
    thundra_agent_lambda_debugger_auth_token: iQnwINa28Vq351P5G815kPdqDxjsnoE4qjLQI6eet/o=
    thundra_apiKey: 52537f73-4e59-4e74-85cf-6518077b731e
  iam:
    role:
      managedPolicies:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  tags:
    service: ${self:service}
    stage: ${self:custom.stage}
  tracing:
    lambda: true
  vpc:
    securityGroupIds:
      - sg-0231973009b21b8e9
    subnetIds:
      - subnet-0a5c738bc43fbb1d7
      - subnet-02c70bb2c910e23c7
      - subnet-0e3947b76b5712e13

functions:
  authorize:
    handler: src/handler.main
    description: Receives a token and validates it against Auth0 IAM provider
    name: ${self:custom.stage}-authorize
    provisionedConcurrency: ${self:custom.provisionedConcurrency.${self:custom.stage}}
    environment:
      AUTH0_CLIENT_ID: ${env:AUTH0_CLIENT_ID}
      AUTH0_CLIENT_PUBLIC_KEY: ${env:AUTH0_CLIENT_PUBLIC_KEY}
      AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}
    tags:
      service: ${self:service}
      stage: ${self:custom.stage}

resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
