service: jwt-authorizer

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${opt:profile, self:custom.defaultProfile}
  region: ${opt:region, 'eu-west-1'}
  memorySize: ${self:custom.memorySize.${self:provider.stage}}
  description: Lambda for enabling custom authorization using Cimpress Auth0.
  endpointType: edge
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

functions:
  authorize:
    handler: index.handler
    description: Receives a token an validate it against cimpress Auth0
    environment:
      TOKEN_ISSUER: "https://cimpress.auth0.com/"
      JWKS_URI: "https://cimpress.auth0.com/.well-known/jwks.json"
      AUDIENCE: "https://api.cimpress.io/"
      COAM_URL: "https://api.cimpress.io/auth/access-management"
      INCLUDE_PERMISSIONS: "true"
    tags:
      Cost Center: pct
      Owner: shelley
      Customer: platform

custom:
  defaultStage: dev 
  defaultProfile: ${env:CI_SERVERLESS_PROFILE,'vbu-product-catalog@admin'}
  memorySize:
    dev: 128
    prod: 128

package:
  exclude:
    - tests/**
    - coverage/**
    - performance.yml
    - "*.md"
    - "event.json*"
    - node_modules/aws-sdk/**
    - CODEOWNERS
    - LICENSE