service: auth0-custom-authorizer

useDotenv: true

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline

custom:
  endpointType: regional
  profile: ${opt:profile, 'souschef'}
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, env:STAGE, 'dev'}
  logRetentionInDays:
    dev: 7
    prod: 30
  memorySize:
    dev: 128
    prod: 128
  provisionedConcurrency:
    dev: 1
    prod: 
  timeout:
    dev: 6
    prod: 12

provider:
  name: aws
  description: Lambda custom authorizer for Auth0 IAM provider
  endpointType: ${self:custom.endpointType}
  lambdaHashingVersion: 20201221
  logRetentionInDays: ${self:custom.logRetentionInDays.${self:custom.stage}}
  memorySize: ${self:custom.memorySize.${self:custom.stage}}
  profile: ${self:custom.profile}
  region: ${self:custom.region}
  runtime: nodejs14.x
  stage: ${self:custom.stage}
  timeout: ${self:custom.timeout.${self:custom.stage}}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  tags:
    service: ${self:service}
    stage: ${self:custom.stage}
  tracing:
    lambda: true
  vpc:
    securityGroupIds:
      - sg-0231973009b21b8e9
    subnetIds:
      - subnet-0a5c738bc43fbb1d7
      - subnet-02c70bb2c910e23c7
      - subnet-0e3947b76b5712e13

functions:
  authorize:
    handler: handler.main
    module: src/functions/authorize
    description: Receives a token and validates it against Auth0 IAM provider
    name: ${self:custom.stage}-authorize
    provisionedConcurrency: ${self:custom.provisionedConcurrency.${self:custom.stage}}
    environment:
      AUTH0_CLIENT_ID: ${env:AUTH0_CLIENT_ID}
      AUTH0_CLIENT_PUBLIC_KEY: ${env:AUTH0_CLIENT_PUBLIC_KEY}
      AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}
    tags:
      service: ${self:service}
      stage: ${self:custom.stage}

resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
